name: mapbox_api_pro
description: Unofficial Mapbox Dart SDK that follow official Mapbox documentation.
version: 1.0.1
homepage: https://github.com/Koleshy/mapbox_api_pro

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: